# config.yaml
# Central configuration for the diffusion model (training and generation)

# --- General Settings ---
# Settings related to data and compute
general:
  img_size: 32         # MNIST is 28x28, but we'll pad to 32x32 for convenience
  device: "auto"       # "auto" will use cuda if available, otherwise cpu. Can be "cuda" or "cpu".

# --- File Paths ---
# Location of data, models, and outputs
paths:
  dataset_root: "../data"
  model_save_path: "models/mnist_conditional.pth"
  generation_output_dir: "output"

# --- Diffusion Parameters ---
# Identical for both training and generation
diffusion:
  timesteps: 1000      # Number of noising steps (T)
  beta_start: 0.0001   # 1e-4
  beta_end: 0.02

# --- Training Hyperparameters ---
training:
  epochs: 20
  batch_size: 128
  learning_rate: 0.001 # 1e-3

# --- Generation Settings ---
generation:
  num_samples_per_class: 10  # N_SAMPLES